import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<GotLifeGame<0, [
    'xxxxxxxx',
    'xxxxoxxx',
    'xxooxxxx',
    'xxoxxoox',
    'xxxxxxxx',
    'xxxxoxxx',
    'xxxooxxx',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxxxoxxx',
    'xxooxxxx',
    'xxoxxoox',
    'xxxxxxxx',
    'xxxxoxxx',
    'xxxooxxx',
    'xxxxxxxx',
  ]>>,
  Expect<Equal<GotLifeGame<20, [
   'xxxxxxxx',
    'xxoxxxxx',
    'xoxoxxxx',
    'xoxoxxxx',
    'xxoxxxxx',
    'xxxxxoox',
    'xxxxxoox',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxoxxxxx',
    'xoxoxxxx',
    'xoxoxxxx',
    'xxoxxxxx',
    'xxxxxoox',
    'xxxxxoox',
    'xxxxxxxx',
  ]>>,
  Expect<Equal<GotLifeGame<5, [
    'xxxxxxxx',
    'xxoxxxxx',
    'xxxoxxxx',
    'xoooxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxoxoxxx',
    'xxxooxxx',
    'xxxoxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>>,
  Expect<Equal<GotLifeGame<3, [
    'xxxxxxxx',
    'xoxxxoxx',
    'xxxxoxxx',
    'xxooxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxoooxxx',
    'xxxxxxxx',
    'xxoxoxxx',
    'xxxoxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>>,
  Expect<Equal<GotLifeGame<2, [
    'xxxxxxxx',
    'xxxxxxxx',
    'xxoxxxxx',
    'xxxoxxxx',
    'xxxooxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxoxxxx',
    'xxoxoxxx',
    'xxoxoxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>>,
  Expect<Equal<GotLifeGame<10, [
    'xxxxxxxx',
    'xxxxxxxx',
    'xxoxxxxx',
    'xxxoxxxx',
    'xxxooxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>, [
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
    'xxxxxxxx',
  ]>>,
]
