import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  // All possible color combinations from the COLORS config
  Expect<Equal<
    AppColor,
    | "border"
    | "input"
    | "ring"
    | "background"
    | "foreground"
    | "foreground-light"
    | "foreground-title"
    | "foreground-title2"
    | "primary"
    | "primary-dark"
    | "primary-light"
    | "primary-foreground"
    | "secondary"
    | "secondary-dark"
    | "secondary-light"
    | "secondary-foreground"
    | "destructive"
    | "destructive-dark"
    | "destructive-light"
    | "destructive-foreground"
    | "info"
    | "info-dark"
    | "info-light"
    | "info-foreground"
    | "warning"
    | "warning-dark"
    | "warning-light"
    | "warning-foreground"
    | "success"
    | "success-dark"
    | "success-light"
    | "success-foreground"
    | "muted"
    | "muted-foreground"
    | "accent"
    | "accent-foreground"
    | "hover"
    | "popover"
    | "popover-foreground"
    | "card"
    | "card-foreground"
  >>,
]
