import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<MyUppercase<'foobar'>, 'FOOBAR'>>,
  Expect<Equal<MyUppercase<'FOOBAR'>, 'FOOBAR'>>,
  Expect<Equal<MyUppercase<''>, ''>>,
  Expect<Equal<MyUppercase<' \n hellO ts !'>, ' \n HELLO TS !'>>,
  Expect<Equal<MyUppercase<'a'>, 'A'>>,
  Expect<Equal<MyUppercase<'b'>, 'B'>>,
  Expect<Equal<MyUppercase<'c'>, 'C'>>,
  Expect<Equal<MyUppercase<'d'>, 'D'>>,
  Expect<Equal<MyUppercase<'e'>, 'E'>>,
  Expect<Equal<MyUppercase<'f'>, 'F'>>,
  Expect<Equal<MyUppercase<'g'>, 'G'>>,
  Expect<Equal<MyUppercase<'h'>, 'H'>>,
  Expect<Equal<MyUppercase<'i'>, 'I'>>,
  Expect<Equal<MyUppercase<'j'>, 'J'>>,
  Expect<Equal<MyUppercase<'k'>, 'K'>>,
  Expect<Equal<MyUppercase<'l'>, 'L'>>,
  Expect<Equal<MyUppercase<'m'>, 'M'>>,
  Expect<Equal<MyUppercase<'n'>, 'N'>>,
  Expect<Equal<MyUppercase<'o'>, 'O'>>,
  Expect<Equal<MyUppercase<'p'>, 'P'>>,
  Expect<Equal<MyUppercase<'q'>, 'Q'>>,
  Expect<Equal<MyUppercase<'r'>, 'R'>>,
  Expect<Equal<MyUppercase<'s'>, 'S'>>,
  Expect<Equal<MyUppercase<'t'>, 'T'>>,
  Expect<Equal<MyUppercase<'u'>, 'U'>>,
  Expect<Equal<MyUppercase<'v'>, 'V'>>,
  Expect<Equal<MyUppercase<'w'>, 'W'>>,
  Expect<Equal<MyUppercase<'x'>, 'X'>>,
  Expect<Equal<MyUppercase<'y'>, 'Y'>>,
  Expect<Equal<MyUppercase<'z'>, 'Z'>>,
]
